# ── _config.yml ──

remote_theme: "mmistakes/minimal-mistakes@4.25.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: "dark"    # built‑in skins include "dark", "default", "air", "mint", etc. :contentReference[oaicite:0]{index=0}
# other settings
baseurl: "/panagiotismavritsakis.github.io"  
url: "https://pargo18.github.io"

nav:
  - title: "Curriculum Vitae"
    url: "https://pargo18.github.io/panagiotismavritsakis.github.io/cv/"
  - title: "Projects"
    url:   "https://pargo18.github.io/panagiotismavritsakis.github.io/projects/"
  - title: "Research"
    url: "https://pargo18.github.io/panagiotismavritsakis.github.io/research/"